[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
mint_nft = "7bgMods6RnePcWYhQ3eRZN6xf29EQdiBbtVmUat2BYYR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/dawn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
